<?php
 			define('SERVER','localhost');
 			define('DB_USERID','root');
 			define('DB_PASSWORD','');
 			define('DATABASE','matrimonial_project');
			define('PROJECT_TITLE','matri');
			define('PROJECT_SUBTITLE','');
			define('THEME','Primary');
			define('ERRORPAGE','');
 			?>